Update nextjs.yml

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -2,6 +2,7 @@
 #
 # To get started with Next.js see: https://nextjs.org/docs/getting-started
 #
+
 name: Deploy Next.js site to Raspberry PI
 
 on:
@@ -32,6 +33,21 @@ jobs:
     build:
         runs-on: ubuntu-latest
         steps:
+            
+        - name: Debug Secrets
+            run: |
+                if [[ -z "${{ secrets.TS_OAUTH_CLIENT_ID }}" ]]; then
+                    echo "::error title=Missing Secret::TS_OAUTH_CLIENT_ID is empty"
+                    exit 1
+                else
+                  echo "TS_OAUTH_CLIENT_ID is set"
+                fi
+                if [[ -z "${{ secrets.TS_OAUTH_SECRET }}" ]]; then
+                    echo "::error title=Missing Secret::TS_OAUTH_SECRET is empty"
+                    exit 1
+                else
+                  echo "TS_OAUTH_SECRET is set"
+                fi
             - name: Checkout
               uses: actions/checkout@v4
             - uses: pnpm/action-setup@v4
@@ -58,6 +74,7 @@ jobs:
                       ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.json', '**/yarn.lock') }}-
             - name: Build with Next.js
               run: pnpm run build
+              
             - name: Setup Tailscale
               uses: tailscale/github-action@v3
               with:
